package com.estockmarket.app.bean;

import java.sql.Time;
import java.util.Date;

import org.springframework.data.annotation.Id;
//import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//@Document(collection = "stock")
@DynamoDBTable(tableName = "stock")
public class Stock {
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	private String stockId;
	@DynamoDBAttribute
	private String stockName;
	@DynamoDBAttribute
	private String companyCode;
	@DynamoDBAttribute
	private double stockPrice;
	@JsonFormat(pattern = "yyyy-MM-dd")
	private Date stockDate;
	@DynamoDBAttribute
	private String stockTime;
	public String getStockId() {
		return stockId;
	}
	public void setStockId(String stockId) {
		this.stockId = stockId;
	}
	public String getStockName() {
		return stockName;
	}
	public void setStockName(String stockName) {
		this.stockName = stockName;
	}
	public String getCompanyCode() {
		return companyCode;
	}
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	public double getStockPrice() {
		return stockPrice;
	}
	public void setStockPrice(double stockPrice) {
		this.stockPrice = stockPrice;
	}
//	@DynamoDBRangeKey
	public Date getStockDate() {
		return stockDate;
	}
	public void setStockDate(Date stockDate) {
		this.stockDate = stockDate;
	}
	public String getStockTime() {
		return stockTime;
	}
	public void setStockTime(String stockTime) {
		this.stockTime = stockTime;
	}
	public Stock(String stockId, String stockName, String companyCode, double stockPrice, Date stockDate,
			String stockTime) {
		super();
		this.stockId = stockId;
		this.stockName = stockName;
		this.companyCode = companyCode;
		this.stockPrice = stockPrice;
		this.stockDate = stockDate;
		this.stockTime = stockTime;
	}
	public Stock() {
		super();
		// TODO Auto-generated constructor stub
	}
	
}
